Auth basique
noctuelles/42-ft_transcendance pull request #1
Opened 2023-01-09 18:45 UTC by dams333

La base du système d'auth est fonctionnelle.

Il manque:
- La vérification des retour d'erreur
- Le renew des refresh_token a chaque utilisation

Exemple d'utilisation de l'auth dans le front:
```ts
function MyComponent() {
    const userContext = React.useContext(UserContext);

    useEffect(() => {
        const token = userContext.getAccessToken();
        fetch(BACK_URL + "/api/endpoint", {
            method: "GET",
            headers: {
                "Content-Type": "application/json",
                Authorization: "Bearer " + token,
            }});
    });
}
```

Exemple d'utilisation de l'auth dans le back:
```ts
@Get('test')
@UseGuards(AuthGuard)
test(@CurrentUser() user: User) {
    return 'Hey ' + user.login;
}
```

2023-01-09 19:59 UTC, jerem-ma requested changes
Super code. Complexe à comprendre à comprendre pour un néophyte comme moi, mais ça a l'air magique et de fonctionner à merveille. Pense bien à remplacer ta fonction magique de 42.js de `processes` à `process` parce que bahh, t'as qu'un seul process quoi, c'est un peu con.
Bisoux.

2023-01-09 20:00 UTC, jerem-ma reviewed
poiet2

2023-01-09 20:02 UTC, jerem-ma submitted a review, later dismissed
Anhh faut faire des changements hein

2023-01-09 20:02 UTC, jerem-ma commented on back/.env.sample
> +DATABASE_URL=postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
pouet

2023-01-09 20:02 UTC, jerem-ma commented on back/package.json
> +        "class-validator": "^0.14.0",
pouet n o 2

2023-01-09 20:03 UTC, jerem-ma commented
Désolé plouvel, je pensais qu'on pouvait delete :'(

2023-01-10 10:25 UTC, dams333 commented
(Jerem m a autorisé a merge ma PR)

2023-01-10 10:25 UTC, merged